/**
 * [INPUT]: 依赖构建阶段 official WorkspaceTypertGenerator 发射的 Host/Remote 面与 DTO declaration。
 * [OUTPUT]: 验证唯一 service、壁纸纯握手/stream、保存 codec 和共享类型出口。
 * [POS]: Host/build integration regression；仅读取静态产物，不执行 descriptor、helper 或 capture。
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */
import assert from 'node:assert/strict'
import test from 'node:test'
import { readFile } from 'node:fs/promises'

const root = new URL('../', import.meta.url)

test('official Host and Remote faces expose one capture namespace with typed save uplink', async () => {
  const host = await readFile(new URL('lib/typert.host.js', root), 'utf8')
  const remote = await readFile(new URL('lib/typert.remote-client.js', root), 'utf8')
  const remoteTypes = await readFile(new URL('lib/typert.remote-client.d.ts', root), 'utf8')
  const publicTypes = await readFile(new URL('lib/types/shared/remote-types.d.ts', root), 'utf8')

  assert.match(host, /Generated by @deepseek-ai\/dsh-typert-generator/)
  assert.match(host, /service: 'pdshWindowCapture'/)
  assert.match(host, /namespace: 'pdshNativeWindowCapture'/)
  assert.match(host, /method: 'capture'/)
  assert.match(host, /method: 'save'/)
  assert.match(host, /method: 'implementationVersion'/)
  assert.match(host, /uplink:/)
  assert.match(remote, /method: 'capture'/)
  assert.match(remote, /method: 'save'/)
  assert.match(remote, /method: 'implementationVersion'/)
  assert.match(remote, /uplink:/)
  for (const descriptor of [host, remote]) {
    assert.deepEqual([...new Set([...descriptor.matchAll(/namespace: '([^']+)'/g)].map(match => match[1]))], ['pdshNativeWindowCapture'])
  }
  assert.match(remoteTypes, /capture: \(signal\?: AbortSignal\) => RemoteStreamHandle<CaptureFrame, never>/)
  assert.match(remoteTypes, /save: \(request: WindowSaveRequest, signal\?: AbortSignal\) => RemoteStreamHandle<WindowSaveFrame, WindowSaveInputFrame>/)
  assert.match(remoteTypes, /'pdshNativeWindowCapture\/capture'/)
  assert.match(publicTypes, /window-capture-protocol\.ts/)
  assert.match(publicTypes, /window-save-protocol\.ts/)
  assert.doesNotMatch(remoteTypes, /\b(?:path|directory|fileNamePattern|saveDirectory)\s*:/)
})

test('official capability faces stay private, version-aligned, typed, and separate from the legacy root face', async () => {
  const rootManifest = JSON.parse(await readFile(new URL('package.json', root), 'utf8'))
  const innerManifest = JSON.parse(await readFile(new URL('lib/runtime-capabilities/package.json', root), 'utf8'))
  const rootHost = await readFile(new URL('lib/typert.host.js', root), 'utf8')
  const rootRemote = await readFile(new URL('lib/typert.remote-client.js', root), 'utf8')
  const host = await readFile(new URL('lib/runtime-capabilities/typert.host.js', root), 'utf8')
  const remote = await readFile(new URL('lib/runtime-capabilities/typert.remote-client.js', root), 'utf8')
  const declaration = await readFile(new URL('lib/runtime-capabilities/typert.remote-client.d.ts', root), 'utf8')

  assert.equal(innerManifest.name, `${rootManifest.name}-capabilities`)
  assert.equal(innerManifest.version, rootManifest.version)
  assert.equal(innerManifest.private, true)
  assert.equal(innerManifest.type, 'module')
  assert.deepEqual(innerManifest.exports, {
    '.': './typert.host.js',
    './typert': { types: './typert.host.d.ts', default: './typert.host.js' },
    './remote': { types: './typert.remote-client.d.ts', default: './typert.remote-client.js' },
    './types': { types: './types/shared/remote-types.d.ts' },
  })
  assert.deepEqual(Object.keys(innerManifest).sort(), ['exports', 'name', 'private', 'type', 'version'])
  for (const descriptor of [rootHost, rootRemote]) {
    assert.ok(descriptor.includes(`package: '${rootManifest.name}'`))
    assert.deepEqual([...new Set([...descriptor.matchAll(/namespace: '([^']+)'/g)].map(match => match[1]))], ['pdshNativeWindowCapture'])
    assert.match(descriptor, /method: 'wallpaper'/)
    assert.doesNotMatch(descriptor, /method: 'captureGeometry(?:Registered)?'/,
      'native geometry must not mutate the fixed base face')
  }
  for (const descriptor of [host, remote]) {
    assert.match(descriptor, /Generated by @deepseek-ai\/dsh-typert-generator/)
    assert.ok(descriptor.includes(`package: '${innerManifest.name}'`))
    assert.deepEqual([...new Set([...descriptor.matchAll(/namespace: '([^']+)'/g)].map(match => match[1]))], ['pdshRuntimeCapabilities'])
    for (const method of ['implementationVersion', 'wallpaperRegistered', 'wallpaper', 'captureGeometryRegistered', 'captureGeometry']) {
      assert.match(descriptor, new RegExp(`method: '${method}'`))
    }
    assert.doesNotMatch(descriptor, /method: '(?:capture|save)'/)
  }
  assert.match(host, /service: 'pdshRuntimeCapabilities'/)
  assert.match(declaration, /from '@daftai\/pdsh-capabilities\/types'/)
  assert.match(declaration, /'pdshRuntimeCapabilities\/implementationVersion'/)
  assert.match(declaration, /'pdshRuntimeCapabilities': TypertRemoteNamespace/)
  assert.doesNotMatch(declaration, /'pdshNativeWindowCapture':/)
  assert.match(declaration, /implementationVersion: \(\) => Promise<RemoteResult<string>>/)
  assert.match(declaration, /wallpaperRegistered: \(\) => Promise<RemoteResult<boolean>>/)
  assert.match(declaration, /wallpaper: \(request: WallpaperRequest, signal\?: AbortSignal\) => RemoteStreamHandle<WallpaperFrame, never>/)
  assert.match(declaration, /captureGeometryRegistered: \(\) => Promise<RemoteResult<boolean>>/)
  assert.match(declaration, /captureGeometry: \(pngSha256: string\) => Promise<RemoteResult<CaptureGeometry \| null>>/)

  const declarations = ['capture-export', 'remote-types', 'window-capture-protocol', 'window-save-protocol', 'system-wallpaper-protocol']
  for (const name of declarations) {
    const original = await readFile(new URL(`lib/types/shared/${name}.d.ts`, root))
    const copy = await readFile(new URL(`lib/runtime-capabilities/types/shared/${name}.d.ts`, root))
    assert.ok(original.equals(copy), `${name}.d.ts must remain byte-identical`)
  }
})

test('official generator emits wallpaper on the same namespace with public DTO declarations', async () => {
  const host = await readFile(new URL('lib/typert.host.js', root), 'utf8')
  const remote = await readFile(new URL('lib/typert.remote-client.js', root), 'utf8')
  const declaration = await readFile(new URL('lib/typert.remote-client.d.ts', root), 'utf8')
  const publicTypes = await readFile(new URL('lib/types/shared/remote-types.d.ts', root), 'utf8')
  for (const descriptor of [host, remote]) {
    assert.match(descriptor, /method: 'wallpaper'/)
    assert.match(descriptor, /method: 'wallpaperRegistered'/)
    assert.deepEqual([...new Set([...descriptor.matchAll(/namespace: '([^']+)'/g)].map(match => match[1]))], ['pdshNativeWindowCapture'])
  }
  assert.match(declaration, /wallpaper: \(request: WallpaperRequest, signal\?: AbortSignal\) => RemoteStreamHandle<WallpaperFrame, never>/)
  assert.match(declaration, /wallpaperRegistered: \(\) => Promise<RemoteResult<boolean>>/)
  assert.match(publicTypes, /system-wallpaper-protocol\.ts/)
  const dto = await readFile(new URL('lib/types/shared/system-wallpaper-protocol.d.ts', root), 'utf8')
  assert.match(dto, /system-wallpaper-tahoe-day/)
  assert.doesNotMatch(dto, /\b(?:path|url|directory)\??\s*:/i)
})
