/**
 * [INPUT]: 依赖构建阶段 official WorkspaceTypertGenerator 发射的 Host/Remote 面与 DTO declaration。
 * [OUTPUT]: 防止 service、namespace、双向 uplink codec 或共享类型出口偏离当前 Host/Client 调用合同。
 * [POS]: Host/build integration regression；仅读取静态产物，不执行 descriptor、helper 或 capture。
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */
import assert from 'node:assert/strict'
import test from 'node:test'
import { readFile } from 'node:fs/promises'

const root = new URL('../', import.meta.url)

test('official Host and Remote faces expose one capture namespace with typed save uplink', async () => {
  const host = await readFile(new URL('lib/typert.host.js', root), 'utf8')
  const remote = await readFile(new URL('lib/typert.remote-client.js', root), 'utf8')
  const remoteTypes = await readFile(new URL('lib/typert.remote-client.d.ts', root), 'utf8')
  const publicTypes = await readFile(new URL('lib/types/shared/remote-types.d.ts', root), 'utf8')

  assert.match(host, /Generated by @deepseek-ai\/dsh-typert-generator/)
  assert.match(host, /service: 'pdshWindowCapture'/)
  assert.match(host, /namespace: 'pdshNativeWindowCapture'/)
  assert.match(host, /method: 'capture'/)
  assert.match(host, /method: 'save'/)
  assert.match(host, /uplink:/)
  assert.match(remote, /method: 'capture'/)
  assert.match(remote, /method: 'save'/)
  assert.match(remote, /uplink:/)
  assert.match(remoteTypes, /capture: \(signal\?: AbortSignal\) => RemoteStreamHandle<CaptureFrame, never>/)
  assert.match(remoteTypes, /save: \(request: WindowSaveRequest, signal\?: AbortSignal\) => RemoteStreamHandle<WindowSaveFrame, WindowSaveInputFrame>/)
  assert.match(publicTypes, /window-capture-protocol\.ts/)
  assert.match(publicTypes, /window-save-protocol\.ts/)
  assert.doesNotMatch(remoteTypes, /\b(?:path|directory|fileNamePattern|saveDirectory)\s*:/)
})
