/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _daftai_pdsh_capabilities_pdshRuntimeCapabilities_captureGeometry_parameter_0$schema$value
const _daftai_pdsh_capabilities_pdshRuntimeCapabilities_captureGeometry_parameter_0$schema = () => (_daftai_pdsh_capabilities_pdshRuntimeCapabilities_captureGeometry_parameter_0$schema$value ??= z.string())
let _daftai_pdsh_capabilities_pdshRuntimeCapabilities_captureGeometry_result$schema$value
const _daftai_pdsh_capabilities_pdshRuntimeCapabilities_captureGeometry_result$schema = () => (_daftai_pdsh_capabilities_pdshRuntimeCapabilities_captureGeometry_result$schema$value ??= z.object({
  'x': z.number().readonly(),
  'y': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'pointPixelScale': z.number().readonly(),
}))
let _daftai_pdsh_capabilities_pdshRuntimeCapabilities_captureGeometryRegistered_result$schema$value
const _daftai_pdsh_capabilities_pdshRuntimeCapabilities_captureGeometryRegistered_result$schema = () => (_daftai_pdsh_capabilities_pdshRuntimeCapabilities_captureGeometryRegistered_result$schema$value ??= z.boolean())
let _daftai_pdsh_capabilities_pdshRuntimeCapabilities_implementationVersion_result$schema$value
const _daftai_pdsh_capabilities_pdshRuntimeCapabilities_implementationVersion_result$schema = () => (_daftai_pdsh_capabilities_pdshRuntimeCapabilities_implementationVersion_result$schema$value ??= z.string())
let _daftai_pdsh_capabilities_pdshRuntimeCapabilities_wallpaper_parameter_0$schema$value
const _daftai_pdsh_capabilities_pdshRuntimeCapabilities_wallpaper_parameter_0$schema = () => (_daftai_pdsh_capabilities_pdshRuntimeCapabilities_wallpaper_parameter_0$schema$value ??= z.union([z.object({
  'kind': z.literal("list"),
}), z.object({
  'kind': z.literal("load"),
  'id': z.string(),
})]))
let _daftai_pdsh_capabilities_pdshRuntimeCapabilities_wallpaper_result$schema$value
const _daftai_pdsh_capabilities_pdshRuntimeCapabilities_wallpaper_result$schema = () => (_daftai_pdsh_capabilities_pdshRuntimeCapabilities_wallpaper_result$schema$value ??= z.union([z.object({
  'type': z.literal("catalog"),
  'entries': z.array(z.object({
  'id': z.string(),
  'name': z.string(),
  'available': z.boolean(),
  'downloadable': z.boolean(),
})),
}), z.object({
  'type': z.literal("phase"),
  'phase': z.union([z.literal("downloading"), z.literal("decoding")]),
}), z.object({
  'type': z.literal("image"),
  'id': z.string(),
  'sourceType': z.union([z.literal("image"), z.literal("video")]),
  'width': z.number(),
  'height': z.number(),
  'jpegBytes': z.number(),
  'chunkCount': z.number(),
}), z.object({
  'type': z.literal("chunk"),
  'index': z.number(),
  'base64': z.string(),
}), z.object({
  'type': z.literal("terminal"),
  'status': z.union([z.literal("cancelled"), z.literal("busy"), z.literal("disposed"), z.literal("byte-budget-exceeded"), z.literal("helper-failed"), z.literal("invalid-request"), z.literal("listed"), z.literal("loaded"), z.literal("unsupported-platform"), z.literal("not-enabled"), z.literal("unavailable"), z.literal("download-failed"), z.literal("download-certificate-failed"), z.literal("decode-failed"), z.literal("protocol-invalid")]),
})]))
let _daftai_pdsh_capabilities_pdshRuntimeCapabilities_wallpaperRegistered_result$schema$value
const _daftai_pdsh_capabilities_pdshRuntimeCapabilities_wallpaperRegistered_result$schema = () => (_daftai_pdsh_capabilities_pdshRuntimeCapabilities_wallpaperRegistered_result$schema$value ??= z.boolean())

export const TYPERT = {
  package: '@daftai/pdsh-capabilities',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@daftai/pdsh-capabilities#pdshRuntimeCapabilities/captureGeometry',
      service: 'pdshRuntimeCapabilities',
      namespace: 'pdshRuntimeCapabilities',
      method: 'captureGeometry',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'pngSha256',
          wire: 'pngSha256',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@daftai/pdsh-capabilities#pdshRuntimeCapabilities/captureGeometry:pngSha256',
            create: _daftai_pdsh_capabilities_pdshRuntimeCapabilities_captureGeometry_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@daftai/pdsh-capabilities#pdshRuntimeCapabilities/captureGeometry:result',
        create: _daftai_pdsh_capabilities_pdshRuntimeCapabilities_captureGeometry_result$schema,
      },
      sourceLocation: {"file":"packages/pdsh-capabilities/src/host/runtime-capabilities-service.ts","line":47,"column":9},
    },
    {
      id: '@daftai/pdsh-capabilities#pdshRuntimeCapabilities/captureGeometryRegistered',
      service: 'pdshRuntimeCapabilities',
      namespace: 'pdshRuntimeCapabilities',
      method: 'captureGeometryRegistered',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@daftai/pdsh-capabilities#pdshRuntimeCapabilities/captureGeometryRegistered:result',
        create: _daftai_pdsh_capabilities_pdshRuntimeCapabilities_captureGeometryRegistered_result$schema,
      },
      sourceLocation: {"file":"packages/pdsh-capabilities/src/host/runtime-capabilities-service.ts","line":41,"column":3},
    },
    {
      id: '@daftai/pdsh-capabilities#pdshRuntimeCapabilities/implementationVersion',
      service: 'pdshRuntimeCapabilities',
      namespace: 'pdshRuntimeCapabilities',
      method: 'implementationVersion',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@daftai/pdsh-capabilities#pdshRuntimeCapabilities/implementationVersion:result',
        create: _daftai_pdsh_capabilities_pdshRuntimeCapabilities_implementationVersion_result$schema,
      },
      sourceLocation: {"file":"packages/pdsh-capabilities/src/host/runtime-capabilities-service.ts","line":31,"column":9},
    },
    {
      id: '@daftai/pdsh-capabilities#pdshRuntimeCapabilities/wallpaper',
      service: 'pdshRuntimeCapabilities',
      namespace: 'pdshRuntimeCapabilities',
      method: 'wallpaper',
      mode: 'stream',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@daftai/pdsh-capabilities/types#WallpaperRequest',
            create: _daftai_pdsh_capabilities_pdshRuntimeCapabilities_wallpaper_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@daftai/pdsh-capabilities/types#WallpaperFrame',
        create: _daftai_pdsh_capabilities_pdshRuntimeCapabilities_wallpaper_result$schema,
      },
      sourceLocation: {"file":"packages/pdsh-capabilities/src/host/runtime-capabilities-service.ts","line":58,"column":3},
    },
    {
      id: '@daftai/pdsh-capabilities#pdshRuntimeCapabilities/wallpaperRegistered',
      service: 'pdshRuntimeCapabilities',
      namespace: 'pdshRuntimeCapabilities',
      method: 'wallpaperRegistered',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@daftai/pdsh-capabilities#pdshRuntimeCapabilities/wallpaperRegistered:result',
        create: _daftai_pdsh_capabilities_pdshRuntimeCapabilities_wallpaperRegistered_result$schema,
      },
      sourceLocation: {"file":"packages/pdsh-capabilities/src/host/runtime-capabilities-service.ts","line":38,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
