/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  RemoteStreamHandle,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { CaptureFrame, WindowSaveFrame, WindowSaveInputFrame, WindowSaveRequest } from '@daftai/pdsh/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$706473684e617469766557696e646f7743617074757265 {
    capture: (signal?: AbortSignal) => RemoteStreamHandle<CaptureFrame, never>
    implementationVersion: () => Promise<RemoteResult<string>>
    save: (request: WindowSaveRequest, signal?: AbortSignal) => RemoteStreamHandle<WindowSaveFrame, WindowSaveInputFrame>
  }
  interface TypertRemoteMap {
    'pdshNativeWindowCapture/capture': (signal?: AbortSignal) => RemoteStreamHandle<CaptureFrame, never>
    'pdshNativeWindowCapture/implementationVersion': () => Promise<RemoteResult<string>>
    'pdshNativeWindowCapture/save': (request: WindowSaveRequest, signal?: AbortSignal) => RemoteStreamHandle<WindowSaveFrame, WindowSaveInputFrame>
  }
  interface TypertRemoteNamespaceMap {
    'pdshNativeWindowCapture': TypertRemoteNamespace$706473684e617469766557696e646f7743617074757265
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
