/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _daftai_pdsh_pdshNativeWindowCapture_capture_result$schema$value
const _daftai_pdsh_pdshNativeWindowCapture_capture_result$schema = () => (_daftai_pdsh_pdshNativeWindowCapture_capture_result$schema$value ??= z.union([z.object({
  'type': z.literal("phase").readonly(),
  'phase': z.union([z.literal("authorization-required"), z.literal("capture-ready")]).readonly(),
}), z.object({
  'type': z.literal("image").readonly(),
  'scope': z.literal("owned-window").readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'pointPixelScale': z.number().readonly(),
  'pngBytes': z.number().readonly(),
  'chunkCount': z.number().readonly(),
}), z.object({
  'type': z.literal("chunk").readonly(),
  'index': z.number().readonly(),
  'base64': z.string().readonly(),
}), z.object({
  'type': z.literal("terminal").readonly(),
  'status': z.union([z.literal("captured"), z.literal("permission-not-granted"), z.literal("cancelled"), z.literal("busy"), z.literal("disposed"), z.literal("capture-timeout"), z.literal("helper-start-timeout"), z.literal("helper-start-failed"), z.literal("requires-macos-14"), z.literal("api-unavailable"), z.literal("process-changed"), z.literal("window-changed"), z.literal("no-ordinary-window-for-main-pid"), z.literal("ambiguous-multiple-windows-refuse"), z.literal("native-size-invalid-or-over-budget"), z.literal("byte-budget-exceeded"), z.literal("encoded-byte-budget-exceeded"), z.literal("invalid-png"), z.literal("metadata-mismatch"), z.literal("helper-failed")]).readonly(),
})]))
let _daftai_pdsh_pdshNativeWindowCapture_save_parameter_0$schema$value
const _daftai_pdsh_pdshNativeWindowCapture_save_parameter_0$schema = () => (_daftai_pdsh_pdshNativeWindowCapture_save_parameter_0$schema$value ??= z.object({
  'requestId': z.string().readonly(),
  'format': z.union([z.literal("png"), z.literal("jpeg"), z.literal("webp")]).readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'title': z.string().readonly(),
  'capturedAt': z.string().readonly(),
}))
let _daftai_pdsh_pdshNativeWindowCapture_save_uplink$schema$value
const _daftai_pdsh_pdshNativeWindowCapture_save_uplink$schema = () => (_daftai_pdsh_pdshNativeWindowCapture_save_uplink$schema$value ??= z.union([z.object({
  'type': z.literal("chunk").readonly(),
  'index': z.number().readonly(),
  'base64': z.string().readonly(),
}), z.object({
  'type': z.literal("finish").readonly(),
  'chunkCount': z.number().readonly(),
  'byteLength': z.number().readonly(),
  'sha256': z.string().readonly(),
})]))
let _daftai_pdsh_pdshNativeWindowCapture_save_result$schema$value
const _daftai_pdsh_pdshNativeWindowCapture_save_result$schema = () => (_daftai_pdsh_pdshNativeWindowCapture_save_result$schema$value ??= z.union([z.object({
  'type': z.literal("ack").readonly(),
  'requestId': z.string().readonly(),
  'nextIndex': z.number().readonly(),
}), z.object({
  'type': z.literal("receipt").readonly(),
  'requestId': z.string().readonly(),
  'outcome': z.literal("saved").readonly(),
  'format': z.union([z.literal("png"), z.literal("jpeg"), z.literal("webp")]).readonly(),
  'byteLength': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
}), z.object({
  'type': z.literal("terminal").readonly(),
  'requestId': z.string().readonly(),
  'code': z.union([z.literal("cancelled"), z.literal("busy"), z.literal("disposed"), z.literal("invalid-request"), z.literal("invalid-input"), z.literal("invalid-image"), z.literal("save-failed")]).readonly(),
})]))

export const TYPERT = {
  package: '@daftai/pdsh',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@daftai/pdsh#pdshNativeWindowCapture/capture',
      service: 'pdshWindowCapture',
      namespace: 'pdshNativeWindowCapture',
      method: 'capture',
      mode: 'stream',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@daftai/pdsh/types#CaptureFrame',
        create: _daftai_pdsh_pdshNativeWindowCapture_capture_result$schema,
      },
      sourceLocation: {"file":"packages/pdsh/src/host/window-capture-service.ts","line":103,"column":3},
    },
    {
      id: '@daftai/pdsh#pdshNativeWindowCapture/save',
      service: 'pdshWindowCapture',
      namespace: 'pdshNativeWindowCapture',
      method: 'save',
      mode: 'stream',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@daftai/pdsh/types#WindowSaveRequest',
            create: _daftai_pdsh_pdshNativeWindowCapture_save_parameter_0$schema,
          },
        },
      ],
      uplink: {
        codec: {
          mode: 'strict',
          typeSymbol: '@daftai/pdsh/types#WindowSaveInputFrame',
          create: _daftai_pdsh_pdshNativeWindowCapture_save_uplink$schema,
        },
      },
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@daftai/pdsh/types#WindowSaveFrame',
        create: _daftai_pdsh_pdshNativeWindowCapture_save_result$schema,
      },
      sourceLocation: {"file":"packages/pdsh/src/host/window-capture-service.ts","line":133,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "单 Cordis service 拥有 camera 与 save；二者只通过官方 Remote stream 传递像素。",
        "summary": "单 Cordis service 拥有 camera 与 save；二者只通过官方 Remote stream 传递像素。",
        "tags": [],
        "jsDoc": "/** 单 Cordis service 拥有 camera 与 save；二者只通过官方 Remote stream 传递像素。 */",
        "key": "pdshWindowCapture",
        "exportName": "WindowCaptureService",
        "members": [
          {
            "kind": "method",
            "name": "capture",
            "signature": "@Remote({ mode: 'stream' }) capture(signal: AbortSignal): AsyncIterable<CaptureFrame>",
            "summary": "权限只在该 Remote iterable 首次被拉取时经原生 helper 请求。",
            "jsDoc": "/** 权限只在该 Remote iterable 首次被拉取时经原生 helper 请求。 */"
          },
          {
            "kind": "method",
            "name": "save",
            "signature": "@Remote({ mode: 'stream' }) save(request: WindowSaveRequest, signal: AbortSignal): RemoteStream<WindowSaveFrame, WindowSaveInputFrame>",
            "summary": "保存仅接受当前 Config 目录与模板；wire 不含 path/name，像素走有界 uplink。",
            "jsDoc": "/** 保存仅接受当前 Config 目录与模板；wire 不含 path/name，像素走有界 uplink。 */"
          },
          {
            "kind": "method",
            "name": "refreshCaptureEnabled",
            "signature": "refreshCaptureEnabled(): void",
            "summary": "由 Config owner 的 owner-scoped volatile listener 同步调用。",
            "jsDoc": "/** 由 Config owner 的 owner-scoped volatile listener 同步调用。 */"
          }
        ],
        "types": [
          {
            "name": "CaptureChunkFrame",
            "declaration": "export interface CaptureChunkFrame {\n    readonly type: 'chunk';\n    readonly index: number;\n    readonly base64: string;\n}"
          },
          {
            "name": "CaptureFailureCode",
            "declaration": "export type CaptureFailureCode = typeof CAPTURE_FAILURE_CODES[number];"
          },
          {
            "name": "CaptureFrame",
            "declaration": "export type CaptureFrame = CapturePhaseFrame | CaptureImageFrame | CaptureChunkFrame | CaptureTerminalFrame;"
          },
          {
            "name": "CaptureImageFrame",
            "declaration": "export interface CaptureImageFrame {\n    readonly type: 'image';\n    readonly scope: 'owned-window';\n    readonly width: number;\n    readonly height: number;\n    readonly pointPixelScale: number;\n    readonly pngBytes: number;\n    readonly chunkCount: number;\n}"
          },
          {
            "name": "CapturePhase",
            "declaration": "export type CapturePhase = 'authorization-required' | 'capture-ready';"
          },
          {
            "name": "CapturePhaseFrame",
            "declaration": "export interface CapturePhaseFrame {\n    readonly type: 'phase';\n    readonly phase: CapturePhase;\n}"
          },
          {
            "name": "CaptureSaveFormat",
            "declaration": "export type CaptureSaveFormat = typeof CAPTURE_SAVE_FORMATS[number];"
          },
          {
            "name": "CaptureTerminalFrame",
            "declaration": "export interface CaptureTerminalFrame {\n    readonly type: 'terminal';\n    readonly status: 'captured' | CaptureFailureCode;\n}"
          },
          {
            "name": "RemoteStream",
            "declaration": "export type RemoteStream<Out, In = never> = AsyncIterable<Out> & { readonly [STREAM_UPLINK]?: In; };"
          },
          {
            "name": "WindowSaveFailureCode",
            "declaration": "export type WindowSaveFailureCode = 'cancelled' | 'busy' | 'disposed' | 'invalid-request' | 'invalid-input' | 'invalid-image' | 'save-failed';"
          },
          {
            "name": "WindowSaveFrame",
            "declaration": "export type WindowSaveFrame = { readonly type: 'ack'; readonly requestId: string; readonly nextIndex: number; } | { readonly type: 'receipt'; readonly requestId: string; readonly outcome: 'saved'; readonly format: CaptureSaveFormat; readonly byteLength: number; readonly width: number; readonly height: number; } | { readonly type: 'terminal'; readonly requestId: string; readonly code: WindowSaveFailureCode; };"
          },
          {
            "name": "WindowSaveInputFrame",
            "declaration": "export type WindowSaveInputFrame = { readonly type: 'chunk'; readonly index: number; readonly base64: string; } | { readonly type: 'finish'; readonly chunkCount: number; readonly byteLength: number; readonly sha256: string; };"
          },
          {
            "name": "WindowSaveRequest",
            "declaration": "export interface WindowSaveRequest {\n    readonly requestId: string;\n    readonly format: CaptureSaveFormat;\n    readonly width: number;\n    readonly height: number;\n    readonly title: string;\n    readonly capturedAt: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
